### ISSUE TITLE
Failed to Load Extension

### ISSUE THREAD

**Issue by angelsenvy228** [Fire-Input/text-generation-webui-coqui-tts#1]
This is just a question I'm new to github and learning all this AI stuff, sorry for my ignorance. I am on Windows and believe I followed all the directions successfully but when I load the extension I get the below error message

![coquiError](https://github.com/Fire-Input/text-generation-webui-coqui-tts/assets/43688502/4d5b9cd3-8ca5-4080-bbe5-fd7498b3a72c)

I also notice the directions say The coqui_tts extension will automatically download the pretrained model tts_models/en/vctk/vits but when I look I have no tts folder in local C:\Users\USER\AppData\Local\tts.

I added everything to PATH I think, if you can tell what I'm doing wrong or missed I'd really appreciated it, thanks.

**Comment by Fire-Input** [comment]
You didn't do anything wrong.
I did a quick update so it should work with the latest version of both Coqui TTS and Ooba's WebUI now.
